#!/usr/bin/env bash
# Set up a local dev server with offline, chaptered audio.
#
# Both .env and data/ are gitignored, so this script is the committed record of
# how to rebuild the dev environment. Idempotent — safe to re-run.
#
#   ./scripts/dev-fixture.sh          # set up, then print how to start
#   ./scripts/dev-fixture.sh --start  # set up and run the server in foreground
#
# What it produces:
#   .env                             dev token, port 8080, sync effectively off
#   data/library/audio/atp700.mp3    ~107 MB, 17 ID3 CHAP chapters w/ APIC art
#   data/library/dev-local.xml       local feed: one relative + one absolute
#                                    file:// enclosure (exercises both branches
#                                    of resolveEnclosureUrl / path-safety)
#
# The MP3 is a real episode chosen for its chapter track: chapter boundaries are
# what drive the lock screen artwork/title swaps, so it's the only fixture that
# actually tests that path. Note the iOS *simulator* has no Now Playing UI at
# all — lock screen behaviour can only be verified on device.

set -euo pipefail
cd "$(dirname "$0")/.."

TOKEN="${PCAST_TOKEN:-dev-local-worldcast-testing}"
PORT="${PORT:-8080}"
AUDIO_URL="https://atp.fm/audio/vv9utuxur3plunbg/atp700.mp3"
AUDIO_PATH="data/library/audio/atp700.mp3"
AUDIO_BYTES=111797868

mkdir -p data/library/audio

if [ ! -f .env ]; then
  cat > .env <<EOF
# Local dev server (generated by scripts/dev-fixture.sh).
PCAST_TOKEN=$TOKEN
PORT=$PORT
BASE_PATH=
DATA_DIR=./data
# Effectively disables the hourly RSS sync so dev runs don't hammer real feeds.
# The local-library scan still runs on each explicit POST /api/sync.
SYNC_INTERVAL_MS=999999999
LOCAL_LIBRARY_DIR=./data/library
DEBUG=1
EOF
  echo "wrote .env (token: $TOKEN)"
else
  echo ".env exists — left alone"
  TOKEN="$(sed -n 's/^PCAST_TOKEN=//p' .env | head -1)"
  PORT="$(sed -n 's/^PORT=//p' .env | head -1)"
fi

# Size-check rather than just existence, so a truncated download self-heals.
if [ "$(stat -f%z "$AUDIO_PATH" 2>/dev/null || echo 0)" != "$AUDIO_BYTES" ]; then
  echo "downloading fixture audio (~107 MB)…"
  curl -fL --progress-bar -A Worldcast-dev -o "$AUDIO_PATH" "$AUDIO_URL"
else
  echo "fixture audio present — skipping download"
fi

# The absolute enclosure has to be baked with this checkout's real path.
ABS_URL="file://$(cd data/library/audio && pwd)/atp700.mp3"
cat > data/library/dev-local.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/dev-fixture.sh — edit that, not this. -->
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>Worldcast Dev (local)</title>
    <link>http://localhost:$PORT/</link>
    <description>Local-library fixture feed for development. Audio is served off
      disk via file:// enclosures, so no network is needed once the MP3 is
      downloaded.</description>
    <itunes:author>Worldcast dev</itunes:author>

    <item>
      <title>Chaptered episode (relative enclosure)</title>
      <guid isPermaLink="false">worldcast-dev-relative-1</guid>
      <pubDate>Mon, 21 Jul 2025 10:00:00 +0000</pubDate>
      <description>Referenced with a path relative to this XML file — exercises
        resolveEnclosureUrl()'s no-scheme branch.</description>
      <itunes:duration>6978</itunes:duration>
      <enclosure url="audio/atp700.mp3" length="$AUDIO_BYTES" type="audio/mpeg"/>
    </item>

    <item>
      <title>Chaptered episode (absolute file:// enclosure)</title>
      <guid isPermaLink="false">worldcast-dev-absolute-1</guid>
      <pubDate>Tue, 22 Jul 2025 10:00:00 +0000</pubDate>
      <description>Same audio via a fully-qualified file:// URL — exercises
        safeFileUrlToPath()'s in-library check.</description>
      <itunes:duration>6978</itunes:duration>
      <enclosure url="$ABS_URL" length="$AUDIO_BYTES" type="audio/mpeg"/>
    </item>
  </channel>
</rss>
EOF
echo "wrote data/library/dev-local.xml"

BASE="http://localhost:$PORT/$TOKEN/"
cat <<EOF

Dev server URL (paste into the iOS app's Settings → Worldcast server):
  $BASE

Start it with:            npm start
Import the local feed:    curl -X POST ${BASE}api/sync
EOF

if [ "${1:-}" = "--start" ]; then
  echo
  exec npm start
fi
